version: '3.3'

services:
  php:
    build:
      context: ./build/php
      dockerfile: Dockerfile
    container_name: academy-php
    volumes:
      - ./html:/var/www/html
      - ./logs:/logs
      - ./build/php/site.ini:/usr/local/etc/php/conf.d/site.ini
    ports:
      - "8080:8080"
    restart: unless-stopped

  db:
    image: mariadb
    restart: unless-stopped
    container_name: academy-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: academy-pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8081:80


  mongodb:
    image: mongo:4.2.8
    container_name: academy-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    restart: unless-stopped

  nginx:
    build:
      context: ./build/nginx
      dockerfile: Dockerfile
    container_name: academy-nginx
    volumes:
      - ./html:/var/www/html
      - ./logs:/logs
      - ./build/nginx/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - 1234:80
    restart: unless-stopped